### ISSUE TITLE
Error while using YAML string formatted scrape target relabeling configuration.

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/prometheus-scrape-config-k8s-operator#32]
### Bug Description

Most of our config options, for instance `relabel_configs`, are required to be YAML formatted:

```yaml
  relabel_configs:
    description: YAML string formatted scrape target relabeling configuration.
    type: string
```

But if you use YAML it fails.

### To Reproduce

1. Deploy this bundle:
```yaml
bundle: kubernetes
applications:
  prometheus:
    charm: prometheus-k8s
    channel: edge
    series: focal
    resources:
      prometheus-image: 128
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  scrape-config:
    charm: prometheus-scrape-config-k8s
    channel: edge
    series: focal
    scale: 1
    options:
      scrape_interval: 12s
      scrape_timeout: 9s
    constraints: arch=amd64
  zinc:
    charm: zinc-k8s
    channel: edge
    resources:
      zinc-image: 120
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
relations:
- - prometheus:metrics-endpoint
  - scrape-config:metrics-endpoint
- - zinc:metrics-endpoint
  - scrape-config:configurable-scrape-jobs
```
2. Create a [relabel config like this one.](https://blog.ruanbekker.com/blog/2022/05/30/prometheus-relabel-config-examples/):
  a. Create a variable with the YAML
     ```shell
      $ relabel="source_labels: [__address__]                                 
      separator: ':'
      regex: '(.*):(.*)'
      replacement: '${1}'
      target_label: instance"
     ```

   b. Add this config: 
      ```shell
       juju config scrape-config relabel_configs=$relabel
      ```
3. Check error while validating scrape jobs:
  ```
   unit-prometheus-0: 16:45:46.874 ERROR unit.prometheus/0.juju-log metrics-endpoint:2: Validating scrape jobs failed: b'time="2023-10-04T19:45:46Z" level=fatal msg="parsing YAML file /tmp/tmpas8qx_44: yaml: unmarshal errors:\\n  line 4: cannot unmarshal !!str `source_...` into []*relabel.Config"\n'
  ```

### Environment

```shell
Model  Controller  Cloud/Region        Version  SLA          Timestamp
cos    microk8s    microk8s/localhost  3.1.5    unsupported  16:46:49-03:00

App            Version  Status  Scale  Charm                         Channel  Rev  Address         Exposed  Message
prometheus     2.46.0   active      1  prometheus-k8s                edge     150  10.152.183.115  no       
scrape-config  n/a      active      1  prometheus-scrape-config-k8s  edge      42  10.152.183.200  no       
zinc           ...      active      1  zinc-k8s                      edge     125  10.152.183.151  no       

Unit              Workload  Agent  Address      Ports  Message
prometheus/0*     active    idle   10.1.38.104         
scrape-config/0*  active    idle   10.1.38.89          
zinc/0*           active    idle   10.1.38.99          

Relation provider               Requirer                                Interface          Type     Message
prometheus:prometheus-peers     prometheus:prometheus-peers             prometheus_peers   peer     
scrape-config:metrics-endpoint  prometheus:metrics-endpoint             prometheus_scrape  regular  
zinc:metrics-endpoint           scrape-config:configurable-scrape-jobs  prometheus_scrape  regular  
zinc:zinc-peers                 zinc:zinc-peers                         zinc_peers         peer   
```

### Relevant log output

```shell
unit-prometheus-0: 16:45:46.874 ERROR unit.prometheus/0.juju-log metrics-endpoint:2: Validating scrape jobs failed: b'time="2023-10-04T19:45:46Z" level=fatal msg="parsing YAML file /tmp/tmpas8qx_44: yaml: unmarshal errors:\\n  line 4: cannot unmarshal !!str `source_...` into []*relabel.Config"\n'
```

**Comment by sed-i** [comment]
This is possibly because the `$relabel` is not quoted and whitespace breaks up.
Can you confirm with `juju config` that the config value matches the expected?

**Comment by lucabello** [comment]
It was indeed a quoting issue. Just tried with the latest revisions, and the following `relabel_config`:

```yaml
# test_scrape_config.yaml
- source_labels: [__address__]
  regex: '(.*)'
  replacement: '${1}'
  target_label: coconut
```

After configuring the charm with:

```bash
∮ juju config scrape-config relabel_configs=@test_scrape_config.yaml
```

You can see the label is correctly added to Prometheus:

![Image](https://github.com/user-attachments/assets/39df90c9-c991-4bfc-b3ef-9333628ee2c6)
